### ISSUE TITLE
Building an app to minimise imports / specify exports

### ISSUE THREAD

**Issue by jrp2014** [shayne-fletcher/ghc-lib-parser-ex#29]
Perhaps this library is too low-level, but I'd like to be able to build an app that 
* generates a minimal import list for a set of modules in a project (and updates the sources)
* figures out all the exports that  are used in modules across a project (and updates the sources)

GHC can be coaxed into generating a nicely-formatted set of minimal imports (by -ddump-minimal-imports) so presumably this library can get at them somehow and update the sources, ideally preserving comments using some heuristic.

Those imports across a project can then be used to generate a minimal list of exports.

I think that this would be helpful for detecting and minimising cruft in old codebases.

Any pointers to where to start would be gratefully received.  Perhaps the app would make a good demo for the library.

**Comment by ndmitchell** [comment]
This library is only the parser. For what you're doing you need the names resolved which is more than this library provides.

**Comment by jrp2014** [comment]
thanks
