### ISSUE TITLE
patToStr and VarPat

### ISSUE THREAD

**Issue by zliu41** [shayne-fletcher/ghc-lib-parser-ex#35]
Should `patToStr` print the var if the input is a `VarPat`, so that `patToStr . strToPar == id`?

**Comment by shayne-fletcher** [comment]
Did you have a use-case in mind?

**Comment by zliu41** [comment]
I don't any more. I was thinking of implementing a new hint in hlint, which would require extracting the var from `VarPat`, but I ended up giving up on the idea. I think `unsafePrettyPrint` would also do the job so it didn't necessarily need `patToStr`.

**Comment by shayne-fletcher** [comment]
Got it!
