### ISSUE TITLE
You should **explicitly** say in README / description that your package doesn't follow PVP

### ISSUE THREAD

**Issue by phadej** [shayne-fletcher/ghc-lib-parser-ex#56]
... which is sad, but I understand your constraints.

**Comment by shayne-fletcher** [comment]
Copy that Oleg. I infer that caused you some bother 😔 Sorry! I'll put a note.

**Comment by phadej** [comment]
No worries, I haven't yet run into problems. I happened to read through README *before* using the lib :)

**Comment by shayne-fletcher** [comment]
Note added in https://github.com/shayne-fletcher/ghc-lib-parser-ex/pull/57.
