### ISSUE TITLE
cabal file on hackage for 8.10.0.20 version depends on ghc = 9.0.*

### ISSUE THREAD

**Issue by mimi1vx** [shayne-fletcher/ghc-lib-parser-ex#89]

**Comment by shayne-fletcher** [comment]
@mimi1vx Thank-you for the report!

**Comment by shayne-fletcher** [comment]
Fixed via https://github.com/shayne-fletcher/ghc-lib-parser-ex/pull/90/commits/eade905dd71df552bf5bed0f501439863a06467f
